const throwError = () => {
  throw new Error('Oh no! Error!')
};

export default throwError;
